### ISSUE TITLE
Remove Login Menu

### ISSUE THREAD

**Issue by zakiego** [zakiego/desa-bambangin-2023#6]
## Code

https://github.com/zakiego/desa-bambangin-2023/blob/main/src/components/UI/Navbar/index.tsx

## Screenshot

- [ ] Desktop Mode

![image](https://github.com/zakiego/desa-bambangin-2023/assets/78015359/0b62ae65-c855-4da5-b43d-978164489448)

- [ ] Mobile Mode

![image](https://github.com/zakiego/desa-bambangin-2023/assets/78015359/5faaa3b0-8118-4e92-b596-2d0e8b3d32d0)

**Comment by sohaibaumer** [comment]
can i get assigned?

**Comment by zakiego** [comment]
> can i get assigned?

Yes of course!
